version: "3.9"

services:
  analysis:
    build:
      context: .
      args:
        R_VERSION: "${R_VERSION:-4.2.0}"
        PYTHON_VERSION: "${PYTHON_VERSION:-3.9.13}"
    image: jannink/analysis
    container_name: jannink_analysis
    volumes:
      - ./scripts:/home/analysis/scripts